config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
    passwords: "users/passwords"
  }
  root to: 'recommends#index'
  resources :users, only: :show
  resources :recommends, only: [:index, :new, :create, :show, :edit, :delete] do
    resources :comments, only:[:create]
    resources :favorites, only: [:create, :destroy]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :recommend
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :recommend, counter_cache: :fav_count
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :recommend
end

app/models/link_url.rb
class LinkUrl < ActiveRecord::Base
  has_many :recommend_urls
  has_many  :recommends, through: :recomennd_urls
end

app/models/recommend.rb
class Recommend < ActiveRecord::Base
  has_many :images
  has_many :comments
  accepts_nested_attributes_for :images
  has_many :recommend_urls
  has_many  :link_urls, through: :recommend_urls
  acts_as_taggable_on :labels
  acts_as_taggable
  acts_as_ordered_taggable_on :recotags
  belongs_to :user
  has_many :favorites, dependent: :destroy
  def favorite_user(user_id)
    favorites.find_by(user_id: user_id)
  end
  mount_uploader :image, ImageUploader
  validates :title, presence: true
end

app/models/recommend_tag.rb
class RecommendTag < ActiveRecord::Base
  belongs_to :recommend
  belongs_to :tag
end

app/models/recommend_url.rb
class RecommendUrl < ActiveRecord::Base
  belongs_to :recommend
  belongs_to :link_url
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :recommend_tags
  has_many  :recommends, through: :recommend_tags
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many  :recommends
  has_many  :favorites
  has_many  :recommends, through: :favorites
  has_many  :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar,
                      styles:  { medium: "300x300#", thumb: "100x100#" }
  validates_attachment_content_type :avatar,
                                      content_type: ["image/jpg","image/jpeg","image/png"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  # deviseのストロングパラメータに追加の記述
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :avatar])
  end
  # サインアウトするとログイン画面に飛ぶ記述
  def after_sign_out_path_for(resource)
    '/users/sign_in'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      respond_to do |format|
        format.html { redirect_to controller: "recommends", action: "show", id: "#{@comment.recommend.id}" }
        format.json
      end
    else
      render controller: "recommends", action: "show", id: "#{@comment.recommend.id}"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body).merge(user_id: current_user.id, recommend_id: params[:recommend_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = Favorite.create(user_id: current_user.id, recommend_id: params[:recommend_id])
    @favorites = Favorite.where(recommend_id: params[:recommend_id])
    @recommends = Recommends.all
  end
  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, recommend_id: params[:recommend_id])
    favorite.destroy
    @favorites = Favorite.where(recommend_id: params[:recommend_id])
    @recommend = Recommend.all
  end
end

app/controllers/recommends_controller.rb
class RecommendsController < ApplicationController

  def index
    @recommends = Recommend.order('created_at DESC')
  end

  def new
    @recommend = Recommend.new
    @recommend.images.build
  end

  def create
    @recommend = Recommend.new(record_params)
    if @recommend.save
      redirect_to root_path
    else
      flash.now[:alert] = "タイトルを入力してください"
      render :new
    end
    # respond_to do |format|
    #   if recommend.save
    #       format.html { redirect_to @recommend, notice: 画像がアップロードされました }
    #       format.json { render json: @recommend, status: :created, location: @recommend }
    #   else
    #     format.html { render action: "new" }
    #     format.json { render json: @recommend.errors, status: :unprocessable_entity  }
  end

  def show
    @recommend = Recommend.find(params[:id])
    @comment = Comment.new
    @comments = @recommend.comments.order('created_at ASC')
    # respond_to do |format|
    #   format.html
    #   format.json
    # end
  end

  def edit
  end

  def delete
  end

  def tag_cloud
    @tags = User.tag_counts_on(:tags).order('count DESC')
  end

  private
  def record_params
    params.require(:recommend).permit(:title, :detail, :recotag_list, images_attributes: [:image]).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/recommends_helper.rb
module RecommendsHelper
end

app/views/favorites/create.js.erb
$("#favorite-link").html("<%= j(render partial: 'recommends_recommend', locals: { recommends: @recommends, favorites: @favorites, favorite: @favorite}) %>")

app/views/favorites/destroy.js.erb
$("#favorite-link").html("<%= j(render partial: 'recommends_recommend', locals: { recommends: @recommends, favorites: @favorites, favorite: @favorite}) %>")

app/views/layouts/_header.html.erb
<header class="header-default">
  <div class="header-default__container">
    <!-- ここからロゴ -->
    <div class="header-default-logo">
      <a class="header-default-logo-icon" href="/">
        <i class="fa fa-hand-spock-o">めこぴ</i>
      </a>
    </div>
    <!-- ここからナブバー -->
    <nav class="header-default-nav">
      <!-- ナブバー/検索ホルダー -->
      <div class="header-default-searchbox">
        <form class="header-searchbox" action="/search/" method="GET" autocomplete="off" ng-controller="HeaderSearchboxController">
          <i class="fa fa-search"></i>
          <input name="search" type="text" class="header-searchbox__input" placeholder="○○を探そう！">
        </form>
      </div>
      <!-- ナブバー/メニューリスト -->
      <ul class="header-default-menu">
        <!-- レコメンド一覧 -->
        <li class="header-default-menu-item__recommend-list">
          <a class= "fa fa-th-list" href=""><span>マイリスト</span></a>
        </li>
        <!-- メッセージ一覧 -->
        <li class="header-default-menu-item__message-list">
          <a class="fa fa-commenting-o" href=""><span>メッセージ</span></a>
        </li>
        <!-- 通知一覧 -->
        <li class="header-default-menu-item__notification-list">
          <a class="fa fa-bell-o" href=""><span>通知</span></a>
        </li>
        <!-- ユーザー機能一覧 -->
        <li class="header-default-menu-item__user">
          <% if user_signed_in? %>
            <%= image_tag  current_user.avatar.url(:thumb) %><span>ユーザー</span>
             <ul class="user-dropdown">
              <li class="user-dropdown-list"><a href="/users/<%= current_user.id %>">プロフィール</a></li>
              <li class="user-dropdown-list"><a href="#">設定</a></li>
              <li class="user-dropdown-list"><a href="/">ログアウト</a></li>
              <li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
              <li class="user-dropdown-list"><a href="#">○○からのお知らせ</a></li>
              <li class="user-dropdown-list"><a href="#">お問い合わせ・通報</a></li>
              <li class="user-dropdown-list"><a href="#">ヘルプ</a></li>
            </ul>
          <% end %>

        </li>
      </ul>
      <!-- ナブバー/新規レコメンド作成ボタン -->
      <%= link_to "新規作成", "/recommends/new", class: "new-recommend" %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trippiece</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recommends/_recommend.html.erb
<div class= "home-main__recommend">
  <!-- 画像ブロック -->
  <div class= "home-main__recommend--thumb">
    <% if info.images.any? %>
      <%= image_tag info.image_url %>
    <% else %>
      <span>画像が有りません</span>
    <% end %>
  </div>
  <div class= "home-main__recommend--description">
    <div class= "home-main__recommend--description-user"><%= image_tag info.user.avatar.to_s %></div>
    <div class= "home-main__recommend--description-title"><%= info.title %></div>
    <div class= "clearfix"></div>
    <div class= "home-main__recommend--description-tag">
      <% info.recotag_list.first(2).each do |t| %>
        <div class=recotag-list><%= t %></div>
      <% end %>
    </div>
    <div class= "home-main__recommend--description-fav">
      <!-- ユーザーが既にお気に入りにしている場合 -->
      <% if info.favorite_user(current_user.id) %>
        <%#= link_to recommend_favorite_path(favorite, recommend_id: info.id), id: 'favorite-link', method: :delete, remote: true do %>
          <i class="fa fa-star"></i>
          <% if info.favorites.any? %>
            <span class="recommend-fav-count"><%= info.fav_count %></span>
          <% else %>
            <span class="recommend-fav-count">0</span>
          <%# end %>
        <% end %>
      <!-- ユーザーがまだお気に入りにしていない場合 -->
      <% else %>
        <%= link_to recommend_favorites_path(info), id: 'favorite-link', method: :post, remote: true do %>
          <i class="fa fa-star"></i>
          <% if info.favorites.any? %>
            <span class="recommend-fav-count"><%= info.fav_count %></span>
          <% else %>
            <span class="recommend-fav-count">0</span>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class= "clearfix"></div>
  </div>
</div>

app/views/recommends/index.html.erb
<div class= "container">
  <div class= "home-featured-content">
    ここに特集の表示
    リンクの貼られた画像をアニメーションで切り替え
  </div>

  <div class= "home-main">
    <div class= "home-main__tab">ここにタブを表示し、クリックで切り替え</div>
    <div class= "home-main__container">
      <div class= "home-main__filter">ここで表示の並び替えなどを行う</div>
      <div class= "home-main__recommends-list">
        <%= render partial: "recommend" %>
      </div>
    </div>
  </div>
</div>

app/views/recommends/show.html.erb
<div class="recommend-detail">
  <!-- タイトルブロック -->
  <div class="title-block">
    <h1 class="recommend-detail"><%= @recommend.title %></h1>
  </div>
  <!-- ここから左側ブロック -->
  <div class="recommend-detail-left">
    <!-- メインブロック -->
    <div class="main-block">
      <!-- 画像 -->
      <div class="main-block__image">
        <!-- スライド１ -->
        <div  class="image_content">
          <%= image_tag @recommend.image_url.to_s %>
        </div>
      </div>
      <!-- 情報 -->
      <div class="main-block__info">
        <!-- 投稿者 -->
        <div class="producer">
          <%= image_tag  @recommend.user.avatar.url(:thumb) %>
          <span class="producer-name"><%= @recommend.user.nickname %></span>
        </div>
        <!-- fav数 -->
        <div class="fav">
          <i class="fa fa-star"></i>
          <span class="fav-count">0</span>
        </div>
        <div class="clearfix"></div>
      </div>
      <!-- なぜ？ -->
      <div class="main-block__why">
        <div class="tags-area">
          <% @recommend.recotag_list.each do |recommend_tag| %>
            <div class="tag"><%= recommend_tag %></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <!-- ここから右側ブロック -->
  <div class="recommend-detail-right">
    <!-- コントロールパネル -->
    <div class="side-controll-panel">
      <!-- 上側 -->
      <div class="controll-panel__main">
        <p class="controll-panel__p1">ステータス</p>
        <p class="controll-panel__p2">申込受付前</p>
      </div>
      <!-- 下側 -->
      <div class="controll-panel__favo-btn">
        <span>
          <i class="fa fa-star"></i>お気に入り
        </span>
      </div>
    </div>
    <!-- SNSシェア -->
    <div class="side-share-block">
      <ul class="side-share-block__list">
        <li class="list_facebook"><a href="" target="_blank" title="Facebook"><i class="fa fa-facebook-official"></i></a></li>
        <li class="list_twitter"><a href="" target="_blank" title="Twitter"><i class="fa fa-twitter-square"></i></a></li>
        <li class="list_google"><a href="" target="_blank" title="Google"><i class="fa fa-google-plus-square"></i></a></li>
      </ul>
    </div>
    <!-- コメント入力と表示欄 -->
    <div class="side-chat-block">
      <!-- コメント入力のブロック -->
      <div class="side-chat-post">
        <%= form_for [@recommend, @comment], url: "#{@recommend.id}/comments" do |f| %>
          <%= f.hidden_field :recommend_id, value: "#{@recommend.id}" %>
          <%= f.text_area :body, placeholder: "コメントを入力してください", class: "text_content" %>
          <div class="chat-post-btn">
            <%= f.submit "投稿する" %>
          </div>
        <% end %>
      </div>
      <!-- コメント表示のブロック -->
      <div class="side-chat-main">
        <% if @comments.any? %>
          <% @comments.each do |comment| %>
            <%= render partial: "comment", locals: {comment: comment} %>
          <% end %>
        <% else %>
          <span>まだコメントはありません</span>
        <% end %>
      </div>
    </div>
  </div>
  <div class="clearfix"></div>
</div>